---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgC4griLlRnXpzFgkLx3CsLfsGxE55qwi1VlfXR4c+8vLVCkhojp2wRx0L/Zf4FnfrsCH5OohbAuaugLD2apS29Fly7SRSBKLhugCk5Xfe9dHC25xjM9PbAC3iYwIeuYbuwJkpk8ijU6sTVVZrJejVkesafF6oaEc0qGGyqBU1Uh1JUAUGILK4JgtCCxezeHGIULqRG/wYoqJvNetPSrH0P6KnWSsLGlMi0G5Ge10QKGE+j3Amigw5qbEza0nN0uEjtZBLXFbMqcpkG7as7UwxH8tGKSM5XHTprtzZTNS2BSIzR78IvKBpUNw7wYclji3+1o3ppwIgkkKtloaDojcdZPJuI1sPN+iJmu21p0OryCnG/9vQJWkW+W2u/Zd+7FX4s319Q5TB+lZQ9F+dFdMxXTfMpn3lOmaPJvkLR8Rjds72K8RAr8XTV4SBhwunHhl9DcXllYfqWhbR+l3nlOZfYfbvv8J2CPLOAUd010Yz3SK7vQfEV7EhjKiYtuLw7Kxwf/TnYsRKtyN1kIw6Obes1G4JSeP83s4r1WrV6Vw1GkqJDlvC93CreDLTJ1xMUNNHGnPqBPvNuKcxJiTHn4WxWL95GYTewuwIPtZpgDVd2UTEwmmM93QA7iMEu1QmfhaEWm+RwO4QgqVx0JlgD0aw2+y7eQVfzmnWCT3wQP3VkAZ6HMp2pQ+ueSzJxnsxTeXCc8K9YmyqfQJeneMTAn/C130CpTyqooQ7QQiXajoWSl23p7c+Mu7dnIqUeRsMq8pft/QBjN1MbkvGE4vYaMB6xSIVy/FGtzKzPmxyT2jmYQ6WKD/okd3iuk+4iapIlyQDbNAuV2gMFpxC/cfDHbvfwHnCiAAt8O7aFy6GVjH6Fk1F2xqMvEqdbBWhAOwzRdvsPfwlEVqq/8yo/ImpQ32SgxRjGTamO6XaiiAZoT6vhtUeVs5QeajsrjDH1PiPJ2llpJyfQj+6Jk45T0bX1zZo6lbvfSkSMu
  template:
    metadata:
      creationTimestamp: null
      name: docker
      namespace: default
    type: kubernetes.io/dockerconfigjson
