---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgC8FIUg801XUjuETj11ZvDfr93eMkamX3/nu2kt8JjGDoP3Ja0D8idlfUJPn/qzcFUfzkN874zgFpWgaDDBNSd5pJynWniCupj29gxXnkCQw8K/TTmFGeXp7Rk/gW9niLVdPRUdc1Y4W/pjN0jrBoW/VbM9YfU2FwpvC5egKjYU3Oob09qSy3IRzRRUWCLZUEduwALy3YqIORzemv32R7GIr7+9AbZZyTeSCv1UK7QEsH16NUb8fgv9Nr8n9fPX1P/P3SWD+hcMzIh6i1bp4JGVgPLz/28GNGReywgS5gulWQvyDo5+shTMZpaBiDC07M89ndp33c23ojCzwUCQzs8uRVTfxyfEQ+B2Tkdl2uHyR2QqkVAlczHKJ+wKmdDWVztFjOPmgbU/21QJZALdACc7e2sBYrt0NhOJwkmV/0KylqzpkRAZBf5G0tR7ZUA7YL3ewCS8N+BVzczvVwQjY8PyWiENlNYORVhwVOYhhdzCp6e/LKeLmNbjyk8D/MRSze8LtJDdv5I28jI4PyMvjT4uXBHjhwJTs/0qSHm7dudjcL/9zyKF3ugOUnHFWb/scHhDGJC0WjQj9NOVjFRQziANFi7jgcjEiU/15imQZmYUxWMGkYZiXLR8JHATeJCYI8CpBonZoO8YCSEcv8HKSBwlNW1Aqw9Zcx0wr6AbwnFK3+XNW31BqfX0z/x12bzKUxhsKt+TPyRgqFvihO2IzoIJeZYXnzU=
    AWS_SECRET_ACCESS_KEY: AgDMzvzFNgHRwA6pGpgoNOIG0Q19aJILPkN1qiCuJ199G04wsHJt6YDwgD69pgsm6PdiQef3ybASND8Fg3vltJPCWcDtWAi9dwcrDdZmavic4EP/X62c7aX7Ak3X2ijUnDFjddUPfZOb05XipmgYdpwPXFbEmIbGlSqOR7rzvQvQNRZI4sjbmgpNlqK2TR1uY9v0OpEo97oRbjgdD8qRabqFh8ycUn021ayHZl4u64WXmFytSl3o5nXmmJ6wVtg+0Jc//rIByPme8gm7VqodlBXjsgJABGeUSmOfmlsVzfLcx01XQ94ixHqxiKv8HX7v2gQ1rw9vVizqO6g2w+HRRf5qHsEnJwvdhkawJ/B1v1ZnACLbgBDrKszLiacaFZWtaYbQg9QhYEVuE8vzN0O9+sKPMXWwfyHbIeR9McoRiBaIP4zPEO9EWmmRgJmifZ/Jh9kL+01+W1upJyj/AOHRp6HZy1OIw+q+TDX36Jv9htuWWo6KNWSBbgQtSprveXb6gDfwZ/iRABefTqCf5/D8PiZScnGJfVCsxEWw4+xqeLgQwZc2fDXFbpd8Eu6Xuk6TV9G5BrIKH/q93EYMWase34sre5x9m2ki1CIQT9XjbvaojPhM2iZVrSRDFO4mv810X6bMEJUS7YmIx44/uP1kFPjkcC3xOCSprDfsygUa5G6SdSvw5PbNYh5PXU1R2Wchbx37++7hKFUBj99GQjKhZojIzSQqZPxLJMpvRSPmUR+aLISIEU+8QXWEaA==
  template:
    metadata:
      creationTimestamp: null
      name: s3-credentials
      namespace: default
    type: Opaque
