name: Lint, Format, Static Code Check and Upload to S3

on:
    pull_request:
      types: [opened, synchronize]
    push:
        branches:
            - master

jobs:

    lint-format-and-static-code-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Cache pip packages
              id: cache-pip
              uses: actions/cache@v4
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
                restore-keys: |
                  ${{ runner.os }}-pip-

            - name: Install pre-commit
              run: pip install pre-commit

            - name: Linting with pre-commit
              run: |
                pre-commit run --all-files

    upload-into-s3:
        runs-on: ubuntu-latest
        needs: lint-format-and-static-code-check
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Cache pip packages
              id: cache-pip
              uses: actions/cache@v4
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
                restore-keys: |
                  ${{ runner.os }}-pip-

            - name: Install s3cmd
              run: pip install s3cmd

            - name: Upload s3_script.py into the S3 bucket
              run: |
                s3cmd --access_key=${{ secrets.AWS_ACCESS_KEY_ID }} \
                      --secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
                      --host-bucket="%(bucket)s.${{ secrets.S3_HOST }}" \
                      --region=${{ secrets.S3_BUCKET_REGION }} \
                      put s3_script.py s3://${{ secrets.S3_BUCKET }}/stackable-demo/s3_script.py
